export { Button } from './primitives/Button'
export type { ButtonProps, ButtonVariant } from './primitives/Button'
export { Input } from './primitives/Input'
export type { InputProps } from './primitives/Input'
export { Select } from './primitives/Select'
export { Textarea } from './primitives/Textarea'
export { Toggle } from './primitives/Toggle'
export type { ToggleProps } from './primitives/Toggle'
export { Badge, Chip } from './primitives/Badge'
export type { BadgeTone } from './primitives/Badge'
export { Card } from './primitives/Card'
export { Panel } from './primitives/Panel'
export { Table } from './primitives/Table'
export type { Column } from './primitives/Table'
export { Tabs } from './primitives/Tabs'
export type { TabItem } from './primitives/Tabs'
export { Progress } from './primitives/Progress'
export { Tooltip } from './primitives/Tooltip'

// Simulador (HUD)
export { DetectionBadge } from './sim/DetectionBadge'
export type { DetectionState } from './sim/DetectionBadge'
export { ConfidenceMeter } from './sim/ConfidenceMeter'
export type { ConfidenceLevel } from './sim/ConfidenceMeter'
export { BatteryGauge } from './sim/BatteryGauge'
export type { BatteryState } from './sim/BatteryGauge'
export { TempGauge } from './sim/TempGauge'
export type { TempState } from './sim/TempGauge'
export { SensorPanel } from './sim/SensorPanel'
export type { SensorKind, SensorState } from './sim/SensorPanel'
export { RtkStatus } from './sim/RtkStatus'
export type { RtkState } from './sim/RtkStatus'
export { HudMetric } from './sim/HudMetric'
export { StatusBar } from './sim/StatusBar'
